import type { SystemContent } from '@dsvault/schema';
import { type ExportFile, type ImportResult, finish, fontStack, firstFamily, idFor, ms, px, uniqueNames } from './util';

// CSS custom properties. Colors: light on :root, dark under
// prefers-color-scheme (guarded by data-theme) and again under
// [data-theme="dark"]. Type styles become classes. Durations get a
// prefers-reduced-motion block.

export function exportCSS(c: SystemContent): ExportFile {
  const t = c.tokens;
  const cn = uniqueNames(t.colors), sn = uniqueNames(t.spacing), rn = uniqueNames(t.radius), bn = uniqueNames(t.breakpoints);
  const zn = uniqueNames(t.zIndex), dn = uniqueNames(t.durations), en = uniqueNames(t.easings), shn = uniqueNames(t.shadows), tn = uniqueNames(t.type);
  const decl = (indent: string, pairs: [string, string][]) => pairs.map(([k, v]) => `${indent}--${k}: ${v};`).join('\n');
  const root: [string, string][] = [
    ...t.colors.map((x, i) => [cn[i]!, x.light] as [string, string]),
    ...t.spacing.map((x, i) => [sn[i]!, `${x.value}px`] as [string, string]),
    ...t.radius.map((x, i) => [rn[i]!, `${x.value}px`] as [string, string]),
    ...t.breakpoints.map((x, i) => [bn[i]!, `${x.value}px`] as [string, string]),
    ...t.zIndex.map((x, i) => [zn[i]!, String(x.value)] as [string, string]),
    ...t.shadows.map((x, i) => [shn[i]!, x.value] as [string, string]),
    ...t.durations.map((x, i) => [dn[i]!, `${x.ms}ms`] as [string, string]),
    ...t.easings.map((x, i) => [en[i]!, x.value] as [string, string]),
  ];
  const dark = t.colors.map((x, i) => [cn[i]!, x.dark] as [string, string]);
  const reduced = t.durations.filter((x) => x.reducedMs != null).map((x) => [dn[t.durations.indexOf(x)]!, `${x.reducedMs}ms`] as [string, string]);
  const parts = [`/* ${c.name || 'Untitled system'} — generated by Design System Vault */`, `:root {\n${decl('  ', root)}\n  color-scheme: light;\n}`];
  if (dark.length) {
    parts.push(`@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${decl('    ', dark)}\n    color-scheme: dark;\n  }\n}`);
    parts.push(`:root[data-theme="dark"] {\n${decl('  ', dark)}\n  color-scheme: dark;\n}`);
  }
  if (reduced.length) parts.push(`@media (prefers-reduced-motion: reduce) {\n  :root {\n${decl('    ', reduced)}\n  }\n}`);
  for (const [i, x] of t.type.entries()) {
    parts.push(`.${tn[i]} {\n  font-family: ${fontStack(x.family)};\n  font-size: ${x.size}px;\n  line-height: ${x.lineHeight}px;\n  font-weight: ${x.weight};${x.letterSpacing ? `\n  letter-spacing: ${x.letterSpacing};` : ''}\n}`);
  }
  return { filename: 'tokens.css', mime: 'text/css', text: parts.join('\n\n') + '\n' };
}

// ---- import ----

function blocks(css: string): { selector: string; body: string; media: string }[] {
  const out: { selector: string; body: string; media: string }[] = [];
  const src = css.replace(/\/\*[\s\S]*?\*\//g, '');
  const walk = (text: string, media: string) => {
    let i = 0;
    while (i < text.length) {
      const open = text.indexOf('{', i);
      if (open < 0) break;
      const selector = text.slice(i, open).trim();
      let depth = 1, j = open + 1;
      while (j < text.length && depth) { if (text[j] === '{') depth++; else if (text[j] === '}') depth--; j++; }
      const body = text.slice(open + 1, j - 1);
      if (selector.startsWith('@media')) walk(body, selector);
      else out.push({ selector, body, media });
      i = j;
    }
  };
  walk(src, '');
  return out;
}

const props = (body: string) => [...body.matchAll(/--([\w-]+)\s*:\s*([^;]+);/g)].map((m) => [m[1]!, m[2]!.trim()] as [string, string]);
const HEX = /^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i;
const COLOR_FN = /^(?:rgb|rgba|hsl|hsla|oklch|oklab|lab|lch|color)\(/i;

export function importCSS(css: string, name = ''): ImportResult {
  const warnings: string[] = [];
  const bs = blocks(css);
  const isRoot = (s: string) => /^(:root|html)(\s*,|$)/.test(s) || s === ':root, [data-theme="light"]';
  const light = new Map<string, string>(), dark = new Map<string, string>(), reduced = new Map<string, string>();
  for (const b of bs) {
    if (/prefers-reduced-motion/.test(b.media)) { for (const [k, v] of props(b.body)) reduced.set(k, v); continue; }
    const darkBlock = /prefers-color-scheme:\s*dark/.test(b.media) || /data-theme=["']?dark/.test(b.selector);
    if (darkBlock) { for (const [k, v] of props(b.body)) dark.set(k, v); continue; }
    if (!b.media && isRoot(b.selector)) for (const [k, v] of props(b.body)) light.set(k, v);
  }
  const t = { colors: [] as any[], spacing: [] as any[], radius: [] as any[], breakpoints: [] as any[], zIndex: [] as any[], shadows: [] as any[], durations: [] as any[], easings: [] as any[], type: [] as any[] };
  for (const [k, v] of light) {
    if (HEX.test(v) || COLOR_FN.test(v)) {
      t.colors.push({ id: idFor('color', k), name: k, light: v, dark: dark.get(k) ?? v, usage: '', role: '' });
    } else if (/^cubic-bezier|^steps\(|^(ease|linear)/.test(v)) {
      t.easings.push({ id: idFor('easing', k), name: k, value: v, usage: '' });
    } else if (ms(v) != null && /(ms|s)$/.test(v)) {
      const r = reduced.has(k) ? ms(reduced.get(k)) : null;
      t.durations.push({ id: idFor('duration', k), name: k, ms: ms(v)!, reducedMs: r, usage: '' });
    } else if (/shadow/i.test(k)) {
      t.shadows.push({ id: idFor('shadow', k), name: k, value: v, usage: '' });
    } else if (/^z(-index)?[-_]|^layer/i.test(k) && /^-?\d+$/.test(v)) {
      t.zIndex.push({ id: idFor('z', k), name: k, value: Number(v), usage: '' });
    } else if (px(v) != null) {
      const group = /radius|round|corner/i.test(k) ? 'radius' : /breakpoint|screen|^bp[-_]/i.test(k) ? 'breakpoints' : /space|gap|gutter|size|pad|margin/i.test(k) ? 'spacing' : null;
      if (group) t[group as 'spacing'].push({ id: idFor(group === 'spacing' ? 'space' : group === 'radius' ? 'radius' : 'bp', k), name: k, value: px(v)!, usage: '' });
      else warnings.push(`Skipped --${k}: couldn’t tell what kind of token it is.`);
    } else {
      warnings.push(`Skipped --${k}: value "${v}" isn’t a color, length or duration.`);
    }
  }
  for (const b of bs) {
    const m = b.selector.match(/^\.([\w-]+)$/);
    if (!m || b.media) continue;
    const decl = Object.fromEntries([...b.body.matchAll(/([\w-]+)\s*:\s*([^;]+);/g)].map((x) => [x[1]!, x[2]!.trim()]));
    const size = px(decl['font-size']);
    if (size == null) continue;
    const lh = decl['line-height'];
    t.type.push({
      id: idFor('type', m[1]!), name: m[1]!, family: firstFamily(decl['font-family'] ?? ''), size,
      lineHeight: px(lh) ?? (lh && !isNaN(+lh) ? +lh * size : Math.round(size * 1.5)),
      weight: Number(decl['font-weight']) || 400, letterSpacing: decl['letter-spacing'] ?? '', sample: '',
    });
  }
  return finish({ name, tokens: t }, warnings);
}
