import type { SystemContent } from '@dsvault/schema';
import { type TextFile, fontStack, uniqueNames } from './util';

// Style Dictionary (v4/v5) source files: light tokens, dark color overrides,
// and a config that builds tokens.css with a dark block.

export function toStyleDictionary(c: SystemContent) {
  const t = c.tokens;
  const group = <T extends { name: string; usage?: string }>(list: T[], value: (x: T) => string | number, type: string) => {
    const n = uniqueNames(list);
    return Object.fromEntries(list.map((x, i) => [n[i], { $value: value(x), $type: type, ...(x.usage ? { $description: x.usage } : {}) }]));
  };
  const base: Record<string, any> = {};
  if (t.colors.length) base.color = group(t.colors, (x) => x.light, 'color');
  if (t.spacing.length) base.spacing = group(t.spacing, (x) => `${x.value}px`, 'dimension');
  if (t.radius.length) base.radius = group(t.radius, (x) => `${x.value}px`, 'dimension');
  if (t.breakpoints.length) base.breakpoint = group(t.breakpoints, (x) => `${x.value}px`, 'dimension');
  if (t.zIndex.length) base['z-index'] = group(t.zIndex, (x) => x.value, 'number');
  if (t.shadows.length) base.shadow = group(t.shadows, (x) => x.value, 'shadow');
  if (t.durations.length) base.duration = group(t.durations, (x) => `${x.ms}ms`, 'duration');
  if (t.easings.length) base.easing = group(t.easings, (x) => x.value, 'cubicBezier');
  if (t.type.length) {
    const n = uniqueNames(t.type);
    base.font = Object.fromEntries(t.type.map((x, i) => [n[i], {
      family: { $value: fontStack(x.family), $type: 'fontFamily' },
      size: { $value: `${x.size}px`, $type: 'dimension' },
      'line-height': { $value: `${x.lineHeight}px`, $type: 'dimension' },
      weight: { $value: x.weight, $type: 'fontWeight' },
      ...(x.letterSpacing ? { 'letter-spacing': { $value: x.letterSpacing, $type: 'dimension' } } : {}),
    }]));
  }
  const dark = t.colors.length ? { color: group(t.colors, (x) => x.dark, 'color') } : {};
  return { base, dark };
}

// Shadows, easings and composite values are passed through as written.
const CONFIG = `// Style Dictionary config generated by Design System Vault.
// Run: npx style-dictionary build --config sd.config.mjs
const passthrough = { transformGroup: 'css', transforms: ['name/kebab'] };
export default [
  {
    source: ['tokens.json'],
    platforms: {
      css: { ...passthrough, buildPath: 'build/', files: [{ destination: 'tokens.css', format: 'css/variables', options: { selector: ':root' } }] },
    },
  },
  {
    include: ['tokens.json'],
    source: ['tokens.dark.json'],
    platforms: {
      css: { ...passthrough, buildPath: 'build/', files: [{ destination: 'tokens.dark.css', format: 'css/variables', options: { selector: ':root[data-theme="dark"]' }, filter: (token) => token.filePath.endsWith('tokens.dark.json') }] },
    },
  },
];
`;

export function exportStyleDictionary(c: SystemContent): TextFile[] {
  const { base, dark } = toStyleDictionary(c);
  return [
    { filename: 'tokens.json', mime: 'application/json', text: JSON.stringify(base, null, 2) + '\n' },
    { filename: 'tokens.dark.json', mime: 'application/json', text: JSON.stringify(dark, null, 2) + '\n' },
    { filename: 'sd.config.mjs', mime: 'text/javascript', text: CONFIG },
  ];
}
