import type { SystemContent } from '@dsvault/schema';
import JSON5 from 'json5';
import { type TextFile, type ImportResult, finish, fontStack, idFor, ms, px, uniqueNames } from './util';

// Tailwind v3 config. Colors point at the CSS custom properties from the CSS
// export, so light and dark both work; everything else is a literal.

const stripPrefix = (n: string, p: RegExp) => n.replace(p, '') || n;

export function toTailwindTheme(c: SystemContent): Record<string, any> {
  const t = c.tokens;
  const cn = uniqueNames(t.colors), sn = uniqueNames(t.spacing), rn = uniqueNames(t.radius), bn = uniqueNames(t.breakpoints);
  const tn = uniqueNames(t.type), dn = uniqueNames(t.durations), en = uniqueNames(t.easings), zn = uniqueNames(t.zIndex), shn = uniqueNames(t.shadows);
  const families: Record<string, string[]> = {};
  for (const x of t.type) if (x.family) families[/mono/i.test(x.family) ? 'mono' : 'sans'] ??= fontStack(x.family).split(',').map((s) => s.trim());
  const theme: Record<string, any> = {
    colors: { transparent: 'transparent', current: 'currentColor', ...Object.fromEntries(cn.map((n) => [n, `var(--${n})`])) },
  };
  if (Object.keys(families).length) theme.fontFamily = families;
  if (t.type.length) theme.fontSize = Object.fromEntries(t.type.map((x, i) => [tn[i], [`${x.size}px`, { lineHeight: `${x.lineHeight}px`, fontWeight: String(x.weight), ...(x.letterSpacing ? { letterSpacing: x.letterSpacing } : {}) }]]));
  const extend: Record<string, any> = {};
  if (t.spacing.length) extend.spacing = Object.fromEntries(t.spacing.map((x, i) => [stripPrefix(sn[i]!, /^space(-|$)/), `${x.value}px`]));
  if (t.radius.length) theme.borderRadius = { none: '0', ...Object.fromEntries(t.radius.map((x, i) => [stripPrefix(rn[i]!, /^radius(-|$)/), `${x.value}px`])), full: '9999px' };
  if (t.breakpoints.length) theme.screens = Object.fromEntries(t.breakpoints.map((x, i) => [stripPrefix(bn[i]!, /^(bp|breakpoint|screen)(-|$)/), `${x.value}px`]));
  if (t.shadows.length) theme.boxShadow = { none: 'none', ...Object.fromEntries(t.shadows.map((x, i) => [stripPrefix(shn[i]!, /^shadow(-|$)/), x.value])) };
  if (t.zIndex.length) extend.zIndex = Object.fromEntries(t.zIndex.map((x, i) => [stripPrefix(zn[i]!, /^z(-index)?(-|$)/), String(x.value)]));
  if (t.durations.length) extend.transitionDuration = Object.fromEntries(t.durations.map((x, i) => [stripPrefix(dn[i]!, /^(dur|duration)(-|$)/), `${x.ms}ms`]));
  if (t.easings.length) extend.transitionTimingFunction = Object.fromEntries(t.easings.map((x, i) => [stripPrefix(en[i]!, /^(ease|easing)(-|$)/), x.value]));
  if (Object.keys(extend).length) theme.extend = extend;
  return theme;
}

export function exportTailwind(c: SystemContent): TextFile {
  const body = JSON.stringify(toTailwindTheme(c), null, 2).replace(/^/gm, '  ').trimStart();
  const text = `/** @type {import('tailwindcss').Config} */\n// ${c.name || 'Untitled system'} — generated by Design System Vault.\n// Colors read the CSS custom properties from tokens.css (the CSS export), so dark mode follows it.\nmodule.exports = {\n  content: ['./src/**/*.{html,js,jsx,ts,tsx}'],\n  theme: ${body},\n  plugins: [],\n};\n`;
  return { filename: 'tailwind.config.js', mime: 'text/javascript', text };
}

/** Text of the object literal that follows `key:` at or after `from`, brace-matched. */
function objectAfter(src: string, key: string): string | null {
  const re = new RegExp(`(?:^|[\\s{,])['"]?${key}['"]?\\s*:\\s*\\{`, 'm');
  const m = re.exec(src);
  if (!m) return null;
  let i = m.index + m[0].length, depth = 1;
  const start = i - 1;
  while (i < src.length && depth) { if (src[i] === '{') depth++; else if (src[i] === '}') depth--; i++; }
  return src.slice(start, i);
}

/**
 * Best-effort import from a tailwind.config.js. Reads literal values only;
 * colors that point at CSS variables can't be resolved here, so import the
 * CSS file for those.
 */
export function importTailwind(source: string, name = ''): ImportResult {
  const warnings: string[] = [];
  const src = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/.*$/gm, '$1');
  const read = (key: string): Record<string, any> => {
    const txt = objectAfter(src, key);
    if (!txt) return {};
    try { return JSON5.parse(txt); } catch { warnings.push(`Couldn’t read the ${key} block: it uses code, not plain values.`); return {}; }
  };
  const colors: any[] = [];
  const walk = (o: Record<string, any>, prefix = '') => {
    for (const [k, v] of Object.entries(o)) {
      const n = prefix ? (k === 'DEFAULT' ? prefix : `${prefix}-${k}`) : k;
      if (typeof v === 'string') {
        if (/^var\(/.test(v)) warnings.push(`Skipped color ${n}: it points at ${v}. Import the CSS file for its value.`);
        else if (!['transparent', 'currentColor', 'inherit'].includes(v)) colors.push({ id: idFor('color', n), name: n, light: v, dark: v, usage: '', role: '' });
      } else if (v && typeof v === 'object') walk(v, n);
    }
  };
  walk(read('colors'));
  const dims = (group: string, o: Record<string, any>, prefix: string) => Object.entries(o).flatMap(([k, v]) => {
    const n = px(v);
    return n == null ? [] : [{ id: idFor(group, `${prefix}${k}`), name: `${prefix}${k}`, value: n, usage: '' }];
  });
  const type = Object.entries(read('fontSize')).flatMap(([k, v]) => {
    const [size, opts] = Array.isArray(v) ? v : [v, {}];
    const s = px(size);
    if (s == null) return [];
    const o = typeof opts === 'string' ? { lineHeight: opts } : opts ?? {};
    return [{ id: idFor('type', k), name: k, family: '', size: s, lineHeight: px(o.lineHeight) ?? (Number(o.lineHeight) ? Number(o.lineHeight) * s : Math.round(s * 1.5)), weight: Number(o.fontWeight) || 400, letterSpacing: o.letterSpacing ?? '', sample: '' }];
  });
  const durations = Object.entries(read('transitionDuration')).flatMap(([k, v]) => {
    const n = ms(v);
    return n == null ? [] : [{ id: idFor('duration', k), name: `duration-${k}`, ms: n, reducedMs: null, usage: '' }];
  });
  const easings = Object.entries(read('transitionTimingFunction')).map(([k, v]) => ({ id: idFor('easing', k), name: `ease-${k}`, value: String(v), usage: '' }));
  return finish({
    name,
    tokens: {
      colors, type, durations, easings,
      spacing: dims('space', read('spacing'), 'space-'),
      radius: dims('radius', read('borderRadius'), 'radius-').filter((r) => r.value < 9999),
      breakpoints: dims('bp', read('screens'), ''),
    },
  }, warnings);
}
